Make actions render their view files by default
hanami/cli pull request #95
Opened 2023-09-11 06:19 UTC by radar

Fixes #93

2023-09-11 06:26 UTC, jodosha requested changes
@radar Thanks for this PR, but there are a few things to change before merging it.

We should still generate a `#handle` signature because it serves as guidance for newcomers, and it's really like the case that after one generates an action, one wants to do something with it. Without the signature, a developer needs to write the method themselves. We want generators to be as much as possible useful.

My suggestion is to do:

```ruby
def handle(*)
end
```

---

The following line should appear or not, according to whether `hanami-view` is bundled or not.

```ruby
response.body = self.class.name
```

2023-09-11 06:30 UTC, timriley commented
@jodosha Given we want the handle method to be _informative_ to users, I feel we should probably generate both params for the method too:

```ruby
def handle(request, response)
```

That way at least users know what they're dealing with. They can always blank out unused params later if they want to.

I feel this will be pretty important to do for 2.1, otherwise _every_ action will get just `handle(*)` for a full stack app, which I think will eventually become annoying to users, especially given most actions will typically end up dealing with request params at minimum.

2023-09-11 07:45 UTC, jodosha commented
@timriley OK, maybe `req, res`? so it's shorter for people to type in the implementation of `#handle`.

2023-09-11 07:47 UTC, timriley commented
@jodosha we actually changed to the full name for this terms in the lead up to 2.0 itself, because it make the arguments less cryptic and more self explanatory. I think it'd be good if we could keep them expanded like this: typing a few letters more isn't all that hard, and it makes the resulting code much more expressive when _read_ (and it'll be read far more than it's written).

2023-09-14 15:52 UTC, jodosha commented
@radar there are specs failing, could you please have a look? Thanks 👍

2023-09-14 20:51 UTC, radar commented
@jodosha Please run the build again here. I've just pushed.

2023-09-16 07:06 UTC, timriley reviewed
The changes here look good, thanks @radar!

I've left one comment about my preference for avoiding the leading underscore on the `request, response` parameter names. I'll see what @jodosha thanks, but after we have resolution on that, this looks good to go 🚀

2023-09-18 07:06 UTC, jodosha commented on lib/hanami/cli/generators/app/action/action.erb
> +<%= module_controller_offset %>  def handle(_request, _response)
@timriley Yes.

2023-09-18 07:10 UTC, jodosha approved these changes

2023-09-18 07:10 UTC, jodosha commented on lib/hanami/cli/generators/app/action/action.erb
> +<%= module_controller_offset %>  def handle(_request, response)
```suggestion
<%= module_controller_offset %>  def handle(request, response)
```

2023-09-18 07:10 UTC, jodosha commented on lib/hanami/cli/generators/app/action/slice_action.erb
> +<%= module_controller_offset %>  def handle(_request, _response)
```suggestion
<%= module_controller_offset %>  def handle(request, response)
```

2023-09-18 07:10 UTC, jodosha commented on lib/hanami/cli/generators/app/action/slice_action.erb
> +<%= module_controller_offset %>  def handle(_request, response)
```suggestion
<%= module_controller_offset %>  def handle(request, response)
```

2023-09-18 07:10 UTC, jodosha commented on spec/unit/hanami/cli/commands/app/generate/action_spec.rb
> +                  def handle(_request, response)
```suggestion
                  def handle(request, response)
```

2023-09-18 07:10 UTC, jodosha commented on spec/unit/hanami/cli/commands/app/generate/action_spec.rb
> +                    def handle(_request, response)
```suggestion
                    def handle(request, response)
```

2023-09-18 07:10 UTC, jodosha commented on spec/unit/hanami/cli/commands/app/generate/action_spec.rb
> +                  def handle(_request, _response)
```suggestion
                  def handle(request, response)
```

2023-09-18 07:10 UTC, jodosha commented on spec/unit/hanami/cli/commands/app/generate/action_spec.rb
> +                    def handle(_request, _response)
```suggestion
                    def handle(request, response)
```

2023-09-18 07:10 UTC, jodosha commented on spec/unit/hanami/cli/commands/app/generate/action_spec.rb
> +                  def handle(_request, response)
```suggestion
                  def handle(request, response)
```

2023-09-18 07:10 UTC, jodosha commented on spec/unit/hanami/cli/commands/app/generate/action_spec.rb
> +                        def handle(_request, response)
```suggestion
                        def handle(request, response)
```

2023-09-18 07:12 UTC, jodosha commented
I couldn't commit all the suggestions in a batch for some reason.

![Screenshot 2023-09-18 at 09 11 40](https://github.com/hanami/cli/assets/5089/1cdf7732-49c4-4a6b-aa86-d6c7ff4a9059)

2023-09-18 07:13 UTC, jodosha commented
@radar Thank you very much. 👍

2023-09-18 07:13 UTC, merged